package entidades;
// Generated 24-may-2017 11:11:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Alertas generated by hbm2java
 */
public class Alertas  implements java.io.Serializable {


     private BigDecimal alertaId;
     private Equipos equipos;
     private Date alertaFecha;
     private String alertaMensaje;
     private BigDecimal alertaEstado;

    public Alertas() {
    }

	
    public Alertas(BigDecimal alertaId, Equipos equipos, Date alertaFecha, BigDecimal alertaEstado) {
        this.alertaId = alertaId;
        this.equipos = equipos;
        this.alertaFecha = alertaFecha;
        this.alertaEstado = alertaEstado;
    }
    public Alertas(BigDecimal alertaId, Equipos equipos, Date alertaFecha, String alertaMensaje, BigDecimal alertaEstado) {
       this.alertaId = alertaId;
       this.equipos = equipos;
       this.alertaFecha = alertaFecha;
       this.alertaMensaje = alertaMensaje;
       this.alertaEstado = alertaEstado;
    }
   
    public BigDecimal getAlertaId() {
        return this.alertaId;
    }
    
    public void setAlertaId(BigDecimal alertaId) {
        this.alertaId = alertaId;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }
    public Date getAlertaFecha() {
        return this.alertaFecha;
    }
    
    public void setAlertaFecha(Date alertaFecha) {
        this.alertaFecha = alertaFecha;
    }
    public String getAlertaMensaje() {
        return this.alertaMensaje;
    }
    
    public void setAlertaMensaje(String alertaMensaje) {
        this.alertaMensaje = alertaMensaje;
    }
    public BigDecimal getAlertaEstado() {
        return this.alertaEstado;
    }
    
    public void setAlertaEstado(BigDecimal alertaEstado) {
        this.alertaEstado = alertaEstado;
    }




}


