package entidades;
// Generated 06-04-2017 06:18:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CondicionesId generated by hbm2java
 */
public class CondicionesId  implements java.io.Serializable {


     private BigDecimal proveedorId;
     private BigDecimal institucionId;

    public CondicionesId() {
    }

    public CondicionesId(BigDecimal proveedorId, BigDecimal institucionId) {
       this.proveedorId = proveedorId;
       this.institucionId = institucionId;
    }
   
    public BigDecimal getProveedorId() {
        return this.proveedorId;
    }
    
    public void setProveedorId(BigDecimal proveedorId) {
        this.proveedorId = proveedorId;
    }
    public BigDecimal getInstitucionId() {
        return this.institucionId;
    }
    
    public void setInstitucionId(BigDecimal institucionId) {
        this.institucionId = institucionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CondicionesId) ) return false;
		 CondicionesId castOther = ( CondicionesId ) other; 
         
		 return ( (this.getProveedorId()==castOther.getProveedorId()) || ( this.getProveedorId()!=null && castOther.getProveedorId()!=null && this.getProveedorId().equals(castOther.getProveedorId()) ) )
 && ( (this.getInstitucionId()==castOther.getInstitucionId()) || ( this.getInstitucionId()!=null && castOther.getInstitucionId()!=null && this.getInstitucionId().equals(castOther.getInstitucionId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProveedorId() == null ? 0 : this.getProveedorId().hashCode() );
         result = 37 * result + ( getInstitucionId() == null ? 0 : this.getInstitucionId().hashCode() );
         return result;
   }   


}


