package entidades;
// Generated 06-04-2017 06:18:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Condiciones generated by hbm2java
 */
public class Condiciones  implements java.io.Serializable {


     private CondicionesId id;
     private Instituciones instituciones;
     private Proveedores proveedores;
     private Double condicionLimite;
     private BigDecimal condicionInstalacion;

    public Condiciones() {
    }

	
    public Condiciones(CondicionesId id, Instituciones instituciones, Proveedores proveedores) {
        this.id = id;
        this.instituciones = instituciones;
        this.proveedores = proveedores;
    }
    public Condiciones(CondicionesId id, Instituciones instituciones, Proveedores proveedores, Double condicionLimite, BigDecimal condicionInstalacion) {
       this.id = id;
       this.instituciones = instituciones;
       this.proveedores = proveedores;
       this.condicionLimite = condicionLimite;
       this.condicionInstalacion = condicionInstalacion;
    }
   
    public CondicionesId getId() {
        return this.id;
    }
    
    public void setId(CondicionesId id) {
        this.id = id;
    }
    public Instituciones getInstituciones() {
        return this.instituciones;
    }
    
    public void setInstituciones(Instituciones instituciones) {
        this.instituciones = instituciones;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Double getCondicionLimite() {
        return this.condicionLimite;
    }
    
    public void setCondicionLimite(Double condicionLimite) {
        this.condicionLimite = condicionLimite;
    }
    public BigDecimal getCondicionInstalacion() {
        return this.condicionInstalacion;
    }
    
    public void setCondicionInstalacion(BigDecimal condicionInstalacion) {
        this.condicionInstalacion = condicionInstalacion;
    }




}


