package entidades;
// Generated 24-may-2017 11:11:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contratos generated by hbm2java
 */
public class Contratos  implements java.io.Serializable {


     private BigDecimal contratoId;
     private Compras compras;
     private Date contratoFecha;
     private String contratoRespUaci;
     private String contratoRespProveedor;
     private String contratoRespDepto;
     private String contratoObservacion;
     private Set mantenimientoses = new HashSet(0);
     private Set instalacioneses = new HashSet(0);
     private Set garantiases = new HashSet(0);

    public Contratos() {
    }

	
    public Contratos(BigDecimal contratoId, Compras compras, Date contratoFecha, String contratoRespUaci, String contratoRespProveedor, String contratoRespDepto) {
        this.contratoId = contratoId;
        this.compras = compras;
        this.contratoFecha = contratoFecha;
        this.contratoRespUaci = contratoRespUaci;
        this.contratoRespProveedor = contratoRespProveedor;
        this.contratoRespDepto = contratoRespDepto;
    }
    public Contratos(BigDecimal contratoId, Compras compras, Date contratoFecha, String contratoRespUaci, String contratoRespProveedor, String contratoRespDepto, String contratoObservacion, Set mantenimientoses, Set instalacioneses, Set garantiases) {
       this.contratoId = contratoId;
       this.compras = compras;
       this.contratoFecha = contratoFecha;
       this.contratoRespUaci = contratoRespUaci;
       this.contratoRespProveedor = contratoRespProveedor;
       this.contratoRespDepto = contratoRespDepto;
       this.contratoObservacion = contratoObservacion;
       this.mantenimientoses = mantenimientoses;
       this.instalacioneses = instalacioneses;
       this.garantiases = garantiases;
    }
   
    public BigDecimal getContratoId() {
        return this.contratoId;
    }
    
    public void setContratoId(BigDecimal contratoId) {
        this.contratoId = contratoId;
    }
    public Compras getCompras() {
        return this.compras;
    }
    
    public void setCompras(Compras compras) {
        this.compras = compras;
    }
    public Date getContratoFecha() {
        return this.contratoFecha;
    }
    
    public void setContratoFecha(Date contratoFecha) {
        this.contratoFecha = contratoFecha;
    }
    public String getContratoRespUaci() {
        return this.contratoRespUaci;
    }
    
    public void setContratoRespUaci(String contratoRespUaci) {
        this.contratoRespUaci = contratoRespUaci;
    }
    public String getContratoRespProveedor() {
        return this.contratoRespProveedor;
    }
    
    public void setContratoRespProveedor(String contratoRespProveedor) {
        this.contratoRespProveedor = contratoRespProveedor;
    }
    public String getContratoRespDepto() {
        return this.contratoRespDepto;
    }
    
    public void setContratoRespDepto(String contratoRespDepto) {
        this.contratoRespDepto = contratoRespDepto;
    }
    public String getContratoObservacion() {
        return this.contratoObservacion;
    }
    
    public void setContratoObservacion(String contratoObservacion) {
        this.contratoObservacion = contratoObservacion;
    }
    public Set getMantenimientoses() {
        return this.mantenimientoses;
    }
    
    public void setMantenimientoses(Set mantenimientoses) {
        this.mantenimientoses = mantenimientoses;
    }
    public Set getInstalacioneses() {
        return this.instalacioneses;
    }
    
    public void setInstalacioneses(Set instalacioneses) {
        this.instalacioneses = instalacioneses;
    }
    public Set getGarantiases() {
        return this.garantiases;
    }
    
    public void setGarantiases(Set garantiases) {
        this.garantiases = garantiases;
    }




}


