package entidades;
// Generated 19-may-2017 12:01:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DepartamentosInstitucion generated by hbm2java
 */
public class DepartamentosInstitucion  implements java.io.Serializable {


     private BigDecimal deptoInstitucionId;
     private Instituciones instituciones;
     private String deptoInstitucionNombre;
     private String deptoInstitucionJefe;
     private String deptoInstitucionDescripcion;
     private Set solicitudeses = new HashSet(0);

    public DepartamentosInstitucion() {
    }

	
    public DepartamentosInstitucion(BigDecimal deptoInstitucionId, Instituciones instituciones, String deptoInstitucionNombre, String deptoInstitucionJefe) {
        this.deptoInstitucionId = deptoInstitucionId;
        this.instituciones = instituciones;
        this.deptoInstitucionNombre = deptoInstitucionNombre;
        this.deptoInstitucionJefe = deptoInstitucionJefe;
    }
    public DepartamentosInstitucion(BigDecimal deptoInstitucionId, Instituciones instituciones, String deptoInstitucionNombre, String deptoInstitucionJefe, String deptoInstitucionDescripcion, Set solicitudeses) {
       this.deptoInstitucionId = deptoInstitucionId;
       this.instituciones = instituciones;
       this.deptoInstitucionNombre = deptoInstitucionNombre;
       this.deptoInstitucionJefe = deptoInstitucionJefe;
       this.deptoInstitucionDescripcion = deptoInstitucionDescripcion;
       this.solicitudeses = solicitudeses;
    }
   
    public BigDecimal getDeptoInstitucionId() {
        return this.deptoInstitucionId;
    }
    
    public void setDeptoInstitucionId(BigDecimal deptoInstitucionId) {
        this.deptoInstitucionId = deptoInstitucionId;
    }
    public Instituciones getInstituciones() {
        return this.instituciones;
    }
    
    public void setInstituciones(Instituciones instituciones) {
        this.instituciones = instituciones;
    }
    public String getDeptoInstitucionNombre() {
        return this.deptoInstitucionNombre;
    }
    
    public void setDeptoInstitucionNombre(String deptoInstitucionNombre) {
        this.deptoInstitucionNombre = deptoInstitucionNombre;
    }
    public String getDeptoInstitucionJefe() {
        return this.deptoInstitucionJefe;
    }
    
    public void setDeptoInstitucionJefe(String deptoInstitucionJefe) {
        this.deptoInstitucionJefe = deptoInstitucionJefe;
    }
    public String getDeptoInstitucionDescripcion() {
        return this.deptoInstitucionDescripcion;
    }
    
    public void setDeptoInstitucionDescripcion(String deptoInstitucionDescripcion) {
        this.deptoInstitucionDescripcion = deptoInstitucionDescripcion;
    }
    public Set getSolicitudeses() {
        return this.solicitudeses;
    }
    
    public void setSolicitudeses(Set solicitudeses) {
        this.solicitudeses = solicitudeses;
    }




}


