package entidades;
// Generated 05-25-2017 11:33:58 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private BigDecimal deptoId;
     private String deptoNombre;
     private Set municipioses = new HashSet(0);

    public Departamentos() {
    }

	
    public Departamentos(BigDecimal deptoId, String deptoNombre) {
        this.deptoId = deptoId;
        this.deptoNombre = deptoNombre;
    }
    public Departamentos(BigDecimal deptoId, String deptoNombre, Set municipioses) {
       this.deptoId = deptoId;
       this.deptoNombre = deptoNombre;
       this.municipioses = municipioses;
    }
   
    public BigDecimal getDeptoId() {
        return this.deptoId;
    }
    
    public void setDeptoId(BigDecimal deptoId) {
        this.deptoId = deptoId;
    }
    public String getDeptoNombre() {
        return this.deptoNombre;
    }
    
    public void setDeptoNombre(String deptoNombre) {
        this.deptoNombre = deptoNombre;
    }
    public Set getMunicipioses() {
        return this.municipioses;
    }
    
    public void setMunicipioses(Set municipioses) {
        this.municipioses = municipioses;
    }




}


