package entidades;
// Generated 19-may-2017 12:01:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DetalleCompras generated by hbm2java
 */
public class DetalleCompras  implements java.io.Serializable {


     private BigDecimal detCompraId;
     private Compras compras;
     private BigDecimal detCompraCantidad;
     private String detCompraDescripcion;
     private double detCompraPrecio;
     private Set equiposes = new HashSet(0);

    public DetalleCompras() {
    }

	
    public DetalleCompras(BigDecimal detCompraId, Compras compras, BigDecimal detCompraCantidad, String detCompraDescripcion, double detCompraPrecio) {
        this.detCompraId = detCompraId;
        this.compras = compras;
        this.detCompraCantidad = detCompraCantidad;
        this.detCompraDescripcion = detCompraDescripcion;
        this.detCompraPrecio = detCompraPrecio;
    }
    public DetalleCompras(BigDecimal detCompraId, Compras compras, BigDecimal detCompraCantidad, String detCompraDescripcion, double detCompraPrecio, Set equiposes) {
       this.detCompraId = detCompraId;
       this.compras = compras;
       this.detCompraCantidad = detCompraCantidad;
       this.detCompraDescripcion = detCompraDescripcion;
       this.detCompraPrecio = detCompraPrecio;
       this.equiposes = equiposes;
    }
   
    public BigDecimal getDetCompraId() {
        return this.detCompraId;
    }
    
    public void setDetCompraId(BigDecimal detCompraId) {
        this.detCompraId = detCompraId;
    }
    public Compras getCompras() {
        return this.compras;
    }
    
    public void setCompras(Compras compras) {
        this.compras = compras;
    }
    public BigDecimal getDetCompraCantidad() {
        return this.detCompraCantidad;
    }
    
    public void setDetCompraCantidad(BigDecimal detCompraCantidad) {
        this.detCompraCantidad = detCompraCantidad;
    }
    public String getDetCompraDescripcion() {
        return this.detCompraDescripcion;
    }
    
    public void setDetCompraDescripcion(String detCompraDescripcion) {
        this.detCompraDescripcion = detCompraDescripcion;
    }
    public double getDetCompraPrecio() {
        return this.detCompraPrecio;
    }
    
    public void setDetCompraPrecio(double detCompraPrecio) {
        this.detCompraPrecio = detCompraPrecio;
    }
    public Set getEquiposes() {
        return this.equiposes;
    }
    
    public void setEquiposes(Set equiposes) {
        this.equiposes = equiposes;
    }




}


