package entidades;
// Generated 24-may-2017 11:11:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleInstalacion generated by hbm2java
 */
public class DetalleInstalacion  implements java.io.Serializable {


     private BigDecimal detInstalacionId;
     private Equipos equipos;
     private Instalaciones instalaciones;
     private String detInstalacionEstadoInicial;
     private String detInstalacionEstadoFinal;
     private String detInstalacionDescripcion;
     private String detInstalacionAutorizadoPor;

    public DetalleInstalacion() {
    }

	
    public DetalleInstalacion(BigDecimal detInstalacionId, Equipos equipos, Instalaciones instalaciones, String detInstalacionEstadoInicial, String detInstalacionEstadoFinal, String detInstalacionAutorizadoPor) {
        this.detInstalacionId = detInstalacionId;
        this.equipos = equipos;
        this.instalaciones = instalaciones;
        this.detInstalacionEstadoInicial = detInstalacionEstadoInicial;
        this.detInstalacionEstadoFinal = detInstalacionEstadoFinal;
        this.detInstalacionAutorizadoPor = detInstalacionAutorizadoPor;
    }
    public DetalleInstalacion(BigDecimal detInstalacionId, Equipos equipos, Instalaciones instalaciones, String detInstalacionEstadoInicial, String detInstalacionEstadoFinal, String detInstalacionDescripcion, String detInstalacionAutorizadoPor) {
       this.detInstalacionId = detInstalacionId;
       this.equipos = equipos;
       this.instalaciones = instalaciones;
       this.detInstalacionEstadoInicial = detInstalacionEstadoInicial;
       this.detInstalacionEstadoFinal = detInstalacionEstadoFinal;
       this.detInstalacionDescripcion = detInstalacionDescripcion;
       this.detInstalacionAutorizadoPor = detInstalacionAutorizadoPor;
    }
   
    public BigDecimal getDetInstalacionId() {
        return this.detInstalacionId;
    }
    
    public void setDetInstalacionId(BigDecimal detInstalacionId) {
        this.detInstalacionId = detInstalacionId;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }
    public Instalaciones getInstalaciones() {
        return this.instalaciones;
    }
    
    public void setInstalaciones(Instalaciones instalaciones) {
        this.instalaciones = instalaciones;
    }
    public String getDetInstalacionEstadoInicial() {
        return this.detInstalacionEstadoInicial;
    }
    
    public void setDetInstalacionEstadoInicial(String detInstalacionEstadoInicial) {
        this.detInstalacionEstadoInicial = detInstalacionEstadoInicial;
    }
    public String getDetInstalacionEstadoFinal() {
        return this.detInstalacionEstadoFinal;
    }
    
    public void setDetInstalacionEstadoFinal(String detInstalacionEstadoFinal) {
        this.detInstalacionEstadoFinal = detInstalacionEstadoFinal;
    }
    public String getDetInstalacionDescripcion() {
        return this.detInstalacionDescripcion;
    }
    
    public void setDetInstalacionDescripcion(String detInstalacionDescripcion) {
        this.detInstalacionDescripcion = detInstalacionDescripcion;
    }
    public String getDetInstalacionAutorizadoPor() {
        return this.detInstalacionAutorizadoPor;
    }
    
    public void setDetInstalacionAutorizadoPor(String detInstalacionAutorizadoPor) {
        this.detInstalacionAutorizadoPor = detInstalacionAutorizadoPor;
    }




}


