package entidades;
// Generated 06-04-2017 06:18:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleSolicitud generated by hbm2java
 */
public class DetalleSolicitud  implements java.io.Serializable {


     private BigDecimal detSolicitudId;
     private ProductosInstitucion productosInstitucion;
     private Solicitudes solicitudes;
     private BigDecimal detSolicitudCantidad;
     private String detSolicitudDescripcion;

    public DetalleSolicitud() {
    }

    public DetalleSolicitud(BigDecimal detSolicitudId, ProductosInstitucion productosInstitucion, Solicitudes solicitudes, BigDecimal detSolicitudCantidad, String detSolicitudDescripcion) {
       this.detSolicitudId = detSolicitudId;
       this.productosInstitucion = productosInstitucion;
       this.solicitudes = solicitudes;
       this.detSolicitudCantidad = detSolicitudCantidad;
       this.detSolicitudDescripcion = detSolicitudDescripcion;
    }
   
    public BigDecimal getDetSolicitudId() {
        return this.detSolicitudId;
    }
    
    public void setDetSolicitudId(BigDecimal detSolicitudId) {
        this.detSolicitudId = detSolicitudId;
    }
    public ProductosInstitucion getProductosInstitucion() {
        return this.productosInstitucion;
    }
    
    public void setProductosInstitucion(ProductosInstitucion productosInstitucion) {
        this.productosInstitucion = productosInstitucion;
    }
    public Solicitudes getSolicitudes() {
        return this.solicitudes;
    }
    
    public void setSolicitudes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }
    public BigDecimal getDetSolicitudCantidad() {
        return this.detSolicitudCantidad;
    }
    
    public void setDetSolicitudCantidad(BigDecimal detSolicitudCantidad) {
        this.detSolicitudCantidad = detSolicitudCantidad;
    }
    public String getDetSolicitudDescripcion() {
        return this.detSolicitudDescripcion;
    }
    
    public void setDetSolicitudDescripcion(String detSolicitudDescripcion) {
        this.detSolicitudDescripcion = detSolicitudDescripcion;
    }




}


