package entidades;
// Generated 05-25-2017 11:33:58 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Municipios generated by hbm2java
 */
public class Municipios  implements java.io.Serializable {


     private BigDecimal municipioId;
     private Departamentos departamentos;
     private String municipioNombre;
     private Set institucioneses = new HashSet(0);
     private Set proveedoreses = new HashSet(0);

    public Municipios() {
    }

	
    public Municipios(BigDecimal municipioId, Departamentos departamentos, String municipioNombre) {
        this.municipioId = municipioId;
        this.departamentos = departamentos;
        this.municipioNombre = municipioNombre;
    }
    public Municipios(BigDecimal municipioId, Departamentos departamentos, String municipioNombre, Set institucioneses, Set proveedoreses) {
       this.municipioId = municipioId;
       this.departamentos = departamentos;
       this.municipioNombre = municipioNombre;
       this.institucioneses = institucioneses;
       this.proveedoreses = proveedoreses;
    }
   
    public BigDecimal getMunicipioId() {
        return this.municipioId;
    }
    
    public void setMunicipioId(BigDecimal municipioId) {
        this.municipioId = municipioId;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public String getMunicipioNombre() {
        return this.municipioNombre;
    }
    
    public void setMunicipioNombre(String municipioNombre) {
        this.municipioNombre = municipioNombre;
    }
    public Set getInstitucioneses() {
        return this.institucioneses;
    }
    
    public void setInstitucioneses(Set institucioneses) {
        this.institucioneses = institucioneses;
    }
    public Set getProveedoreses() {
        return this.proveedoreses;
    }
    
    public void setProveedoreses(Set proveedoreses) {
        this.proveedoreses = proveedoreses;
    }




}


