package entidades;
// Generated 24-may-2017 11:11:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Ofertas generated by hbm2java
 */
public class Ofertas  implements java.io.Serializable {


     private BigDecimal ofertaId;
     private Licitaciones licitaciones;
     private Proveedores proveedores;
     private double ofertaPrecio;
     private String ofertaDescripcion;
     private Set garantiases = new HashSet(0);

    public Ofertas() {
    }

	
    public Ofertas(BigDecimal ofertaId, Licitaciones licitaciones, Proveedores proveedores, double ofertaPrecio, String ofertaDescripcion) {
        this.ofertaId = ofertaId;
        this.licitaciones = licitaciones;
        this.proveedores = proveedores;
        this.ofertaPrecio = ofertaPrecio;
        this.ofertaDescripcion = ofertaDescripcion;
    }
    public Ofertas(BigDecimal ofertaId, Licitaciones licitaciones, Proveedores proveedores, double ofertaPrecio, String ofertaDescripcion, Set garantiases) {
       this.ofertaId = ofertaId;
       this.licitaciones = licitaciones;
       this.proveedores = proveedores;
       this.ofertaPrecio = ofertaPrecio;
       this.ofertaDescripcion = ofertaDescripcion;
       this.garantiases = garantiases;
    }
   
    public BigDecimal getOfertaId() {
        return this.ofertaId;
    }
    
    public void setOfertaId(BigDecimal ofertaId) {
        this.ofertaId = ofertaId;
    }
    public Licitaciones getLicitaciones() {
        return this.licitaciones;
    }
    
    public void setLicitaciones(Licitaciones licitaciones) {
        this.licitaciones = licitaciones;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public double getOfertaPrecio() {
        return this.ofertaPrecio;
    }
    
    public void setOfertaPrecio(double ofertaPrecio) {
        this.ofertaPrecio = ofertaPrecio;
    }
    public String getOfertaDescripcion() {
        return this.ofertaDescripcion;
    }
    
    public void setOfertaDescripcion(String ofertaDescripcion) {
        this.ofertaDescripcion = ofertaDescripcion;
    }
    public Set getGarantiases() {
        return this.garantiases;
    }
    
    public void setGarantiases(Set garantiases) {
        this.garantiases = garantiases;
    }




}


