package entidades;
// Generated 06-04-2017 06:18:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pantallas generated by hbm2java
 */
public class Pantallas  implements java.io.Serializable {


     private BigDecimal pantallaId;
     private String pantallaNombre;
     private String pantallaDescripcion;
     private String pantallaUrl;
     private Set permisoses = new HashSet(0);

    public Pantallas() {
    }

	
    public Pantallas(BigDecimal pantallaId, String pantallaNombre) {
        this.pantallaId = pantallaId;
        this.pantallaNombre = pantallaNombre;
    }
    public Pantallas(BigDecimal pantallaId, String pantallaNombre, String pantallaDescripcion, String pantallaUrl, Set permisoses) {
       this.pantallaId = pantallaId;
       this.pantallaNombre = pantallaNombre;
       this.pantallaDescripcion = pantallaDescripcion;
       this.pantallaUrl = pantallaUrl;
       this.permisoses = permisoses;
    }
   
    public BigDecimal getPantallaId() {
        return this.pantallaId;
    }
    
    public void setPantallaId(BigDecimal pantallaId) {
        this.pantallaId = pantallaId;
    }
    public String getPantallaNombre() {
        return this.pantallaNombre;
    }
    
    public void setPantallaNombre(String pantallaNombre) {
        this.pantallaNombre = pantallaNombre;
    }
    public String getPantallaDescripcion() {
        return this.pantallaDescripcion;
    }
    
    public void setPantallaDescripcion(String pantallaDescripcion) {
        this.pantallaDescripcion = pantallaDescripcion;
    }
    public String getPantallaUrl() {
        return this.pantallaUrl;
    }
    
    public void setPantallaUrl(String pantallaUrl) {
        this.pantallaUrl = pantallaUrl;
    }
    public Set getPermisoses() {
        return this.permisoses;
    }
    
    public void setPermisoses(Set permisoses) {
        this.permisoses = permisoses;
    }




}


