package entidades;
// Generated 05-25-2017 11:33:58 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private BigDecimal proveedorId;
     private Municipios municipios;
     private String proveedorEmpresa;
     private String proveedorContacto;
     private String proveedorTelefono1;
     private String proveedorTelefono2;
     private String proveedorCorreo;
     private String proveedorNit;
     private BigDecimal proveedorInstalacion;
     private double proveedorLimite;
     private String proveedorDescripcion;
     private String proveedorDireccion;
     private Set ofertases = new HashSet(0);
     private Set productosProveedors = new HashSet(0);
     private Set comprases = new HashSet(0);
     private Set mantenimientoses = new HashSet(0);
     private Set instalacioneses = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Proveedores() {
    }

	
    public Proveedores(BigDecimal proveedorId, Municipios municipios, String proveedorEmpresa, String proveedorContacto, BigDecimal proveedorInstalacion, double proveedorLimite) {
        this.proveedorId = proveedorId;
        this.municipios = municipios;
        this.proveedorEmpresa = proveedorEmpresa;
        this.proveedorContacto = proveedorContacto;
        this.proveedorInstalacion = proveedorInstalacion;
        this.proveedorLimite = proveedorLimite;
    }
    public Proveedores(BigDecimal proveedorId, Municipios municipios, String proveedorEmpresa, String proveedorContacto, String proveedorTelefono1, String proveedorTelefono2, String proveedorCorreo, String proveedorNit, BigDecimal proveedorInstalacion, double proveedorLimite, String proveedorDescripcion, String proveedorDireccion, Set ofertases, Set productosProveedors, Set comprases, Set mantenimientoses, Set instalacioneses, Set usuarioses) {
       this.proveedorId = proveedorId;
       this.municipios = municipios;
       this.proveedorEmpresa = proveedorEmpresa;
       this.proveedorContacto = proveedorContacto;
       this.proveedorTelefono1 = proveedorTelefono1;
       this.proveedorTelefono2 = proveedorTelefono2;
       this.proveedorCorreo = proveedorCorreo;
       this.proveedorNit = proveedorNit;
       this.proveedorInstalacion = proveedorInstalacion;
       this.proveedorLimite = proveedorLimite;
       this.proveedorDescripcion = proveedorDescripcion;
       this.proveedorDireccion = proveedorDireccion;
       this.ofertases = ofertases;
       this.productosProveedors = productosProveedors;
       this.comprases = comprases;
       this.mantenimientoses = mantenimientoses;
       this.instalacioneses = instalacioneses;
       this.usuarioses = usuarioses;
    }
   
    public BigDecimal getProveedorId() {
        return this.proveedorId;
    }
    
    public void setProveedorId(BigDecimal proveedorId) {
        this.proveedorId = proveedorId;
    }
    public Municipios getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Municipios municipios) {
        this.municipios = municipios;
    }
    public String getProveedorEmpresa() {
        return this.proveedorEmpresa;
    }
    
    public void setProveedorEmpresa(String proveedorEmpresa) {
        this.proveedorEmpresa = proveedorEmpresa;
    }
    public String getProveedorContacto() {
        return this.proveedorContacto;
    }
    
    public void setProveedorContacto(String proveedorContacto) {
        this.proveedorContacto = proveedorContacto;
    }
    public String getProveedorTelefono1() {
        return this.proveedorTelefono1;
    }
    
    public void setProveedorTelefono1(String proveedorTelefono1) {
        this.proveedorTelefono1 = proveedorTelefono1;
    }
    public String getProveedorTelefono2() {
        return this.proveedorTelefono2;
    }
    
    public void setProveedorTelefono2(String proveedorTelefono2) {
        this.proveedorTelefono2 = proveedorTelefono2;
    }
    public String getProveedorCorreo() {
        return this.proveedorCorreo;
    }
    
    public void setProveedorCorreo(String proveedorCorreo) {
        this.proveedorCorreo = proveedorCorreo;
    }
    public String getProveedorNit() {
        return this.proveedorNit;
    }
    
    public void setProveedorNit(String proveedorNit) {
        this.proveedorNit = proveedorNit;
    }
    public BigDecimal getProveedorInstalacion() {
        return this.proveedorInstalacion;
    }
    
    public void setProveedorInstalacion(BigDecimal proveedorInstalacion) {
        this.proveedorInstalacion = proveedorInstalacion;
    }
    public double getProveedorLimite() {
        return this.proveedorLimite;
    }
    
    public void setProveedorLimite(double proveedorLimite) {
        this.proveedorLimite = proveedorLimite;
    }
    public String getProveedorDescripcion() {
        return this.proveedorDescripcion;
    }
    
    public void setProveedorDescripcion(String proveedorDescripcion) {
        this.proveedorDescripcion = proveedorDescripcion;
    }
    public String getProveedorDireccion() {
        return this.proveedorDireccion;
    }
    
    public void setProveedorDireccion(String proveedorDireccion) {
        this.proveedorDireccion = proveedorDireccion;
    }
    public Set getOfertases() {
        return this.ofertases;
    }
    
    public void setOfertases(Set ofertases) {
        this.ofertases = ofertases;
    }
    public Set getProductosProveedors() {
        return this.productosProveedors;
    }
    
    public void setProductosProveedors(Set productosProveedors) {
        this.productosProveedors = productosProveedors;
    }
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }
    public Set getMantenimientoses() {
        return this.mantenimientoses;
    }
    
    public void setMantenimientoses(Set mantenimientoses) {
        this.mantenimientoses = mantenimientoses;
    }
    public Set getInstalacioneses() {
        return this.instalacioneses;
    }
    
    public void setInstalacioneses(Set instalacioneses) {
        this.instalacioneses = instalacioneses;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


