package entidades;
// Generated 24-may-2017 11:11:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private BigDecimal rolId;
     private String rolNombre;
     private String rolDescripcion;
     private Set permisoses = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(BigDecimal rolId, String rolNombre) {
        this.rolId = rolId;
        this.rolNombre = rolNombre;
    }
    public Roles(BigDecimal rolId, String rolNombre, String rolDescripcion, Set permisoses, Set usuarioses) {
       this.rolId = rolId;
       this.rolNombre = rolNombre;
       this.rolDescripcion = rolDescripcion;
       this.permisoses = permisoses;
       this.usuarioses = usuarioses;
    }
   
    public BigDecimal getRolId() {
        return this.rolId;
    }
    
    public void setRolId(BigDecimal rolId) {
        this.rolId = rolId;
    }
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }
    public String getRolDescripcion() {
        return this.rolDescripcion;
    }
    
    public void setRolDescripcion(String rolDescripcion) {
        this.rolDescripcion = rolDescripcion;
    }
    public Set getPermisoses() {
        return this.permisoses;
    }
    
    public void setPermisoses(Set permisoses) {
        this.permisoses = permisoses;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


