package entidades;
// Generated 19-may-2017 12:01:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solicitudes generated by hbm2java
 */
public class Solicitudes  implements java.io.Serializable {


     private BigDecimal solicitudId;
     private DepartamentosInstitucion departamentosInstitucion;
     private TipoSolicitudes tipoSolicitudes;
     private BigDecimal solicitudCodigo;
     private String solicitudReponsable;
     private Date solicitudFecha;
     private BigDecimal solicitudEstado;
     private String solicitudObservacion;
     private Set aprobadoses = new HashSet(0);
     private Set licitacioneses = new HashSet(0);
     private Set detalleSolicituds = new HashSet(0);

    public Solicitudes() {
    }

	
    public Solicitudes(BigDecimal solicitudId, DepartamentosInstitucion departamentosInstitucion, TipoSolicitudes tipoSolicitudes, BigDecimal solicitudCodigo, String solicitudReponsable, Date solicitudFecha, BigDecimal solicitudEstado, String solicitudObservacion) {
        this.solicitudId = solicitudId;
        this.departamentosInstitucion = departamentosInstitucion;
        this.tipoSolicitudes = tipoSolicitudes;
        this.solicitudCodigo = solicitudCodigo;
        this.solicitudReponsable = solicitudReponsable;
        this.solicitudFecha = solicitudFecha;
        this.solicitudEstado = solicitudEstado;
        this.solicitudObservacion = solicitudObservacion;
    }
    public Solicitudes(BigDecimal solicitudId, DepartamentosInstitucion departamentosInstitucion, TipoSolicitudes tipoSolicitudes, BigDecimal solicitudCodigo, String solicitudReponsable, Date solicitudFecha, BigDecimal solicitudEstado, String solicitudObservacion, Set aprobadoses, Set licitacioneses, Set detalleSolicituds) {
       this.solicitudId = solicitudId;
       this.departamentosInstitucion = departamentosInstitucion;
       this.tipoSolicitudes = tipoSolicitudes;
       this.solicitudCodigo = solicitudCodigo;
       this.solicitudReponsable = solicitudReponsable;
       this.solicitudFecha = solicitudFecha;
       this.solicitudEstado = solicitudEstado;
       this.solicitudObservacion = solicitudObservacion;
       this.aprobadoses = aprobadoses;
       this.licitacioneses = licitacioneses;
       this.detalleSolicituds = detalleSolicituds;
    }
   
    public BigDecimal getSolicitudId() {
        return this.solicitudId;
    }
    
    public void setSolicitudId(BigDecimal solicitudId) {
        this.solicitudId = solicitudId;
    }
    public DepartamentosInstitucion getDepartamentosInstitucion() {
        return this.departamentosInstitucion;
    }
    
    public void setDepartamentosInstitucion(DepartamentosInstitucion departamentosInstitucion) {
        this.departamentosInstitucion = departamentosInstitucion;
    }
    public TipoSolicitudes getTipoSolicitudes() {
        return this.tipoSolicitudes;
    }
    
    public void setTipoSolicitudes(TipoSolicitudes tipoSolicitudes) {
        this.tipoSolicitudes = tipoSolicitudes;
    }
    public BigDecimal getSolicitudCodigo() {
        return this.solicitudCodigo;
    }
    
    public void setSolicitudCodigo(BigDecimal solicitudCodigo) {
        this.solicitudCodigo = solicitudCodigo;
    }
    public String getSolicitudReponsable() {
        return this.solicitudReponsable;
    }
    
    public void setSolicitudReponsable(String solicitudReponsable) {
        this.solicitudReponsable = solicitudReponsable;
    }
    public Date getSolicitudFecha() {
        return this.solicitudFecha;
    }
    
    public void setSolicitudFecha(Date solicitudFecha) {
        this.solicitudFecha = solicitudFecha;
    }
    public BigDecimal getSolicitudEstado() {
        return this.solicitudEstado;
    }
    
    public void setSolicitudEstado(BigDecimal solicitudEstado) {
        this.solicitudEstado = solicitudEstado;
    }
    public String getSolicitudObservacion() {
        return this.solicitudObservacion;
    }
    
    public void setSolicitudObservacion(String solicitudObservacion) {
        this.solicitudObservacion = solicitudObservacion;
    }
    public Set getAprobadoses() {
        return this.aprobadoses;
    }
    
    public void setAprobadoses(Set aprobadoses) {
        this.aprobadoses = aprobadoses;
    }
    public Set getLicitacioneses() {
        return this.licitacioneses;
    }
    
    public void setLicitacioneses(Set licitacioneses) {
        this.licitacioneses = licitacioneses;
    }
    public Set getDetalleSolicituds() {
        return this.detalleSolicituds;
    }
    
    public void setDetalleSolicituds(Set detalleSolicituds) {
        this.detalleSolicituds = detalleSolicituds;
    }




}


