package entidades;
// Generated 06-04-2017 06:18:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoMantenimientos generated by hbm2java
 */
public class TipoMantenimientos  implements java.io.Serializable {


     private BigDecimal tipoMantoId;
     private String tipoMantoNombre;
     private String tipoMantoDescripcion;
     private Set mantenimientoses = new HashSet(0);

    public TipoMantenimientos() {
    }

	
    public TipoMantenimientos(BigDecimal tipoMantoId, String tipoMantoNombre) {
        this.tipoMantoId = tipoMantoId;
        this.tipoMantoNombre = tipoMantoNombre;
    }
    public TipoMantenimientos(BigDecimal tipoMantoId, String tipoMantoNombre, String tipoMantoDescripcion, Set mantenimientoses) {
       this.tipoMantoId = tipoMantoId;
       this.tipoMantoNombre = tipoMantoNombre;
       this.tipoMantoDescripcion = tipoMantoDescripcion;
       this.mantenimientoses = mantenimientoses;
    }
   
    public BigDecimal getTipoMantoId() {
        return this.tipoMantoId;
    }
    
    public void setTipoMantoId(BigDecimal tipoMantoId) {
        this.tipoMantoId = tipoMantoId;
    }
    public String getTipoMantoNombre() {
        return this.tipoMantoNombre;
    }
    
    public void setTipoMantoNombre(String tipoMantoNombre) {
        this.tipoMantoNombre = tipoMantoNombre;
    }
    public String getTipoMantoDescripcion() {
        return this.tipoMantoDescripcion;
    }
    
    public void setTipoMantoDescripcion(String tipoMantoDescripcion) {
        this.tipoMantoDescripcion = tipoMantoDescripcion;
    }
    public Set getMantenimientoses() {
        return this.mantenimientoses;
    }
    
    public void setMantenimientoses(Set mantenimientoses) {
        this.mantenimientoses = mantenimientoses;
    }




}


