package entidades;
// Generated 19-may-2017 12:01:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String usuarioUsuario;
     private Instituciones instituciones;
     private Proveedores proveedores;
     private Roles roles;
     private String usuarioNombre;
     private String usuarioCorreo;
     private String usuarioTelefono;
     private String usuarioContrasenia;
     private BigDecimal usuarioEstado;
     private BigDecimal usuarioBloqueado;

    public Usuarios() {
    }

	
    public Usuarios(String usuarioUsuario, Roles roles, String usuarioNombre, String usuarioCorreo, String usuarioContrasenia, BigDecimal usuarioEstado, BigDecimal usuarioBloqueado) {
        this.usuarioUsuario = usuarioUsuario;
        this.roles = roles;
        this.usuarioNombre = usuarioNombre;
        this.usuarioCorreo = usuarioCorreo;
        this.usuarioContrasenia = usuarioContrasenia;
        this.usuarioEstado = usuarioEstado;
        this.usuarioBloqueado = usuarioBloqueado;
    }
    public Usuarios(String usuarioUsuario, Instituciones instituciones, Proveedores proveedores, Roles roles, String usuarioNombre, String usuarioCorreo, String usuarioTelefono, String usuarioContrasenia, BigDecimal usuarioEstado, BigDecimal usuarioBloqueado) {
       this.usuarioUsuario = usuarioUsuario;
       this.instituciones = instituciones;
       this.proveedores = proveedores;
       this.roles = roles;
       this.usuarioNombre = usuarioNombre;
       this.usuarioCorreo = usuarioCorreo;
       this.usuarioTelefono = usuarioTelefono;
       this.usuarioContrasenia = usuarioContrasenia;
       this.usuarioEstado = usuarioEstado;
       this.usuarioBloqueado = usuarioBloqueado;
    }
   
    public String getUsuarioUsuario() {
        return this.usuarioUsuario;
    }
    
    public void setUsuarioUsuario(String usuarioUsuario) {
        this.usuarioUsuario = usuarioUsuario;
    }
    public Instituciones getInstituciones() {
        return this.instituciones;
    }
    
    public void setInstituciones(Instituciones instituciones) {
        this.instituciones = instituciones;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }
    
    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }
    public String getUsuarioCorreo() {
        return this.usuarioCorreo;
    }
    
    public void setUsuarioCorreo(String usuarioCorreo) {
        this.usuarioCorreo = usuarioCorreo;
    }
    public String getUsuarioTelefono() {
        return this.usuarioTelefono;
    }
    
    public void setUsuarioTelefono(String usuarioTelefono) {
        this.usuarioTelefono = usuarioTelefono;
    }
    public String getUsuarioContrasenia() {
        return this.usuarioContrasenia;
    }
    
    public void setUsuarioContrasenia(String usuarioContrasenia) {
        this.usuarioContrasenia = usuarioContrasenia;
    }
    public BigDecimal getUsuarioEstado() {
        return this.usuarioEstado;
    }
    
    public void setUsuarioEstado(BigDecimal usuarioEstado) {
        this.usuarioEstado = usuarioEstado;
    }
    public BigDecimal getUsuarioBloqueado() {
        return this.usuarioBloqueado;
    }
    
    public void setUsuarioBloqueado(BigDecimal usuarioBloqueado) {
        this.usuarioBloqueado = usuarioBloqueado;
    }




}


